### PR TITLE
cr8 sumdata fcn

### LINKED ISSUE #91: Check the summarization and move into separate function
https://github.com/SafetyGraphics/nep-explorer/blob/29e001dfa60266390251cb87bfc0de5a2c79a5eb/R/creatinine_scatter_mod.R#L40

to

https://github.com/SafetyGraphics/nep-explorer/blob/29e001dfa60266390251cb87bfc0de5a2c79a5eb/R/creatinine_scatter_mod.R#L120

### PR DESCRIPTION
**Pull request by jwoolfolk**
Partial Update to Issue #91 - Create Separate Creatinine Data Level and Patient Level Stages Datasets, **Add Unit Test Still Needed.**

closes #91

### CODE REVIEW

**Comment by pburnsdata** [comment]
Nice work on this @jwoolfolk! Before we merge it in, can you move the function to it's own file?

**Review by pburnsdata — CHANGES_REQUESTED** [review]
This looks great! @jwoolfolk nice work. Could you move this function to it's own file before we merge it in?

**Comment by jwoolfolk** [comment]
sure that works!

**Comment by jwoolfolk** [comment]
> This looks great! @jwoolfolk nice work. Could you move this function to it's own file before we merge it in?

@pburnsdata @elimillera @lgakava - creatinine_scatter_mod.R updated to move creatinine_data_fcn to individual file with same name.

**Review by pburnsdata — APPROVED** [review]
It's perfect, thanks @jwoolfolk !

**Pull request merged**
